application: djangoadminongae
version: 1
runtime: python25
api_version: 1
threadsafe: yes

builtins:
- admin_redirect: on
- appstats: on
- remote_api: on

admin_console:
  pages:
  - name: Django Admin
    url: /admin

inbound_services:
- mail
- warmup

handlers:
- url: /_ah/queue/deferred
  #script: djangoappengine.deferred.handler.application
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  #script: djangoappengine.appstats.application
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: "7d"

- url: /.*
  #script: djangoappengine.main.application
  script: djangoappengine/main/main.py
